### ISSUE TITLE
Include the copy icon or suggest including it directly

### ISSUE THREAD

**Issue by Pezmc** [mamezou-tech/eleventy-plugin-code-clipboard#8]
The readme currently suggests including material design icons for the default mdi-content-copy icon.

However, that library is currently 392 KB of fonts and 53.1 KB of CSS, which feels a lot for a single icon. The library itself suggests no longer using the webfont: https://pictogrammers.com/docs/guides/webfont-alternatives/

One workaround could be for people to include the icon directly in their CSS:

```css
.mdi {
    display: inline-block;
    width: 1em;
    height: 1em;
    background-color: currentColor;
    -webkit-mask: no-repeat center / 100%;
    mask: no-repeat center / 100%;
    -webkit-mask-image: var(--svg);
    mask-image: var(--svg);
}
.mdi.mdi-content-copy {
    --svg: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' width='24' height='24'%3E%3Cpath fill='black' d='M19 21H8V7h11m0-2H8a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h11a2 2 0 0 0 2-2V7a2 2 0 0 0-2-2m-3-4H4a2 2 0 0 0-2 2v14h2V3h12V1Z'/%3E%3C/svg%3E");
}
```

The [webfont alternatives page](https://pictogrammers.com/docs/guides/webfont-alternatives/) has alternative suggestions.
